name: Update ORCID Publications
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday
  workflow_dispatch:      # Allows manual trigger
  push:
    branches:
      - main

jobs:
  update-publications:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update ORCID Publications
        uses: jamesgeorge007/github-readme-orcid@v1
        with:
          orcid: '0000-0001-7019-3766'
          file: 'README.md'
