name: Update ORCID Publications
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-publications:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update ORCID
        uses: x-actions/orcid-profile-readme@v1 # A popular, maintained option
        with:
          orcid: '0000-0001-7019-3766'
          file: 'README.md'
